# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g4Cp7og7sJ-ZoPFpBZ9Z4jz2iHMJaQjI

**Reasoning**:
The subtask requires installing the kaggle library, which can be done using pip.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install kaggle

"""## Download dataset

### Subtask:
Download the dataset using the Kaggle API.

**Reasoning**:
Create a directory and download the dataset using the Kaggle API.
"""

import os

# Create a directory named 'kaggle_dataset'
os.makedirs('kaggle_dataset', exist_ok=True)

# Download the dataset using the Kaggle API into the created directory
import subprocess
subprocess.run(["kaggle", "datasets", "download", "-d", "masoudnickparvar/brain-tumor-mri-dataset", "-p", "kaggle_dataset"])

import pandas as pd
import numpy as np

"""# Task
Perform basic preprocessing on the image dataset located at "/content/brain-tumor-mri-dataset.zip", including loading, resizing, normalizing, and splitting the data.

## Load images

### Subtask:
Load the images from the unzipped dataset.

**Reasoning**:
Import necessary libraries, define the dataset path, create empty lists, and iterate through the directories and image files to load the images and their labels.
"""

import os
from collections import Counter
from PIL import Image
import matplotlib.pyplot as plt
from torchvision import datasets

data_dir = "brain-tumor-mri-dataset"

# Function to count images per class
def count_images(path):
    counts = {}
    for class_name in os.listdir(path):
        class_path = os.path.join(path, class_name)
        if os.path.isdir(class_path):
            counts[class_name] = len(os.listdir(class_path))
    return counts

train_counts = count_images(os.path.join(data_dir, "Training"))
test_counts  = count_images(os.path.join(data_dir, "Testing"))

print("Training set distribution:", train_counts)
print("Testing set distribution:", test_counts)

# Collect image sizes from training data
sizes = []
train_path = os.path.join(data_dir, "Training")

for class_name in os.listdir(train_path):
    class_path = os.path.join(train_path, class_name)
    for img_file in os.listdir(class_path)[:50]:  # check first 50 images per class
        img_path = os.path.join(class_path, img_file)
        with Image.open(img_path) as img:
            sizes.append(img.size)

print("Sample image sizes:", sizes[:10])
print("Most common size:", Counter(sizes).most_common(5))

# Collect image sizes from training data
sizes = []
train_path = os.path.join(data_dir, "Training")

for class_name in os.listdir(train_path):
    class_path = os.path.join(train_path, class_name)
    for img_file in os.listdir(class_path)[:50]:  # check first 50 images per class
        img_path = os.path.join(class_path, img_file)
        with Image.open(img_path) as img:
            sizes.append(img.size)

print("Sample image sizes:", sizes[:10])
print("Most common size:", Counter(sizes).most_common(5))

dataset = datasets.ImageFolder(root=os.path.join(data_dir, "Training"))

# Show one image per class
fig, axes = plt.subplots(1, 4, figsize=(12, 3))
class_names = dataset.classes

for idx, class_name in enumerate(class_names):
    class_dir = os.path.join(train_path, class_name)
    img_file = os.listdir(class_dir)[0]
    img_path = os.path.join(class_dir, img_file)
    img = Image.open(img_path)
    axes[idx].imshow(img, cmap="gray")
    axes[idx].set_title(class_name)
    axes[idx].axis("off")

plt.show()

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# Add resize transform so all images are the same size
transform = transforms.Compose([
    transforms.Resize((224, 224)),  # Resize to ViT input size
    transforms.ToTensor()
])

dataset = datasets.ImageFolder("brain-tumor-mri-dataset/Training", transform=transform)
loader = DataLoader(dataset, batch_size=64, shuffle=False)

mean = 0.0
std = 0.0
total_images = 0

for images, _ in loader:
    batch_samples = images.size(0)  # batch size
    images = images.view(batch_samples, images.size(1), -1)  # flatten H, W
    mean += images.mean(2).sum(0)
    std += images.std(2).sum(0)
    total_images += batch_samples

mean /= total_images
std /= total_images

print("Dataset mean:", mean)
print("Dataset std:", std)

from torchvision import transforms

# Replace with your actual dataset mean & std
custom_mean = [0.1855, 0.1855, 0.1855]
custom_std  =[0.1813, 0.1813, 0.1813]

train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.Lambda(lambda img: img.convert("RGB")),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize(mean=custom_mean, std=custom_std)
])

test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.Lambda(lambda img: img.convert("RGB")),
    transforms.ToTensor(),
    transforms.Normalize(mean=custom_mean, std=custom_std)
])

from torchvision import datasets
from torch.utils.data import DataLoader

train_data = datasets.ImageFolder("brain-tumor-mri-dataset/Training", transform=train_transform)
test_data  = datasets.ImageFolder("brain-tumor-mri-dataset/Testing", transform=test_transform)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True, num_workers=2)
test_loader  = DataLoader(test_data, batch_size=32, shuffle=False, num_workers=2)

print("Classes:", train_data.classes)

import os

data_dir = "brain-tumor-mri-dataset"

def count_images(path):
    counts = {}
    for class_name in os.listdir(path):
        class_path = os.path.join(path, class_name)
        if os.path.isdir(class_path):
            counts[class_name] = len(os.listdir(class_path))
    return counts

train_path = os.path.join(data_dir, "Training")
test_path  = os.path.join(data_dir, "Testing")

train_counts = count_images(train_path)
test_counts  = count_images(test_path)

print("Training set distribution:")
for cls, cnt in train_counts.items():
    print(f"{cls}: {cnt} images")

print("\nTesting set distribution:")
for cls, cnt in test_counts.items():
    print(f"{cls}: {cnt} images")

